=== harrytyp/comiupscale/scummvm/fork/devtools/create_ultima/files/ultima4/conf/dtd/graphics.dtd
<!-- $Id: graphics.dtd 2926 2011-06-24 21:48:05Z darren_janeczek $ -->

<!ENTITY % bool '( true | false )'>
<!ENTITY % fixup '( none | intro | abyss | abacus | dungns | blackTransparencyHack | fmtownsscreen )'>
<!ENTITY % layouttype '( standard | gem | dungeon_gem )'>
<!ENTITY % transformtype '( invert | pixel | scroll | frame | pixel_color )'>
<!ENTITY % context '( frame | dir )'>

<!ELEMENT graphics ( imageset | layout | tileanimset )+ >

<!ELEMENT imageset ( image+ ) >
<!ATTLIST imageset name           NMTOKEN  #REQUIRED
                   extends        NMTOKEN  #IMPLIED>

<!ELEMENT image ( subimage* ) >
<!ATTLIST image name              NMTOKEN  #REQUIRED
                filename          CDATA    #REQUIRED
                width             NMTOKEN  #IMPLIED
                height            NMTOKEN  #IMPLIED
                depth             NMTOKEN  #IMPLIED
                prescale          NMTOKEN  #IMPLIED
                filetype          CDATA    #IMPLIED
                tiles             NMTOKEN  #IMPLIED
                introOnly         %bool;   #IMPLIED
                transparentIndex  NMTOKEN  #IMPLIED
                xu4Graphic        %bool;   #IMPLIED
                fixup             %fixup;  #IMPLIED>

<!ELEMENT subimage EMPTY >
<!ATTLIST subimage name           NMTOKEN  #REQUIRED
                   x              NMTOKEN  #IMPLIED
                   y              NMTOKEN  #IMPLIED
                   width          NMTOKEN  #REQUIRED
                   height         NMTOKEN  #REQUIRED>

<!ELEMENT layout ( tileshape, viewport ) >
<!ATTLIST layout name             CDATA    #REQUIRED
                 type             %layouttype; #REQUIRED>

<!ELEMENT tileshape EMPTY >
<!ATTLIST tileshape width         NMTOKEN  #REQUIRED
                    height        NMTOKEN  #REQUIRED>

<!ELEMENT viewport EMPTY >
<!ATTLIST viewport x              NMTOKEN  #REQUIRED
                   y              NMTOKEN  #REQUIRED
                   width          NMTOKEN  #REQUIRED
                   height         NMTOKEN  #REQUIRED>

<!ELEMENT tileanimset ( tileanim+ ) >
<!ATTLIST tileanimset name        NMTOKEN  #REQUIRED>

<!ELEMENT tileanim ( transform+ | context+ ) >
<!ATTLIST tileanim name           NMTOKEN  #REQUIRED
                   random         NMTOKEN  #IMPLIED>

<!ELEMENT context ( transform+ ) >
<!ATTLIST context type            %context; #REQUIRED
                  frame           NMTOKEN   #IMPLIED
                  dir             NMTOKEN   #IMPLIED>

<!ELEMENT transform ( color* ) >
<!ATTLIST transform type          %transformtype; #REQUIRED
                    x             NMTOKEN  #IMPLIED
                    y             NMTOKEN  #IMPLIED
                    width         NMTOKEN  #IMPLIED
                    height        NMTOKEN  #IMPLIED
                    random        NMTOKEN  #IMPLIED
                    increment     NMTOKEN  #IMPLIED>  <!-- If not provided, equals scale -->

=== harrytyp/comiupscale/scummvm/fork/devtools/create_ultima/files/ultima4/conf/graphics.xml
<?xml version="1.0"?>
<!DOCTYPE graphics SYSTEM "dtd/graphics.dtd">
<!-- $Id: graphics.xml 3045 2012-06-17 17:27:52Z twschulz $ -->
<graphics>
    <imageset name="EGA">
        <!-- tiles, charset, and game border -->
        <image name="tiles"    filename="shapes.ega" width="16" height="4096" depth="4" filetype="image/x-u4raw" tiles="256" fixup="blackTransparencyHack">
            <subimage name="tile_sea" x="0" y="0" width="16" height="16"/>
            <subimage name="tile_water"         width="16" height="16"/>
            <subimage name="tile_shallows"      width="16" height="16"/>
            <subimage name="tile_swamp"         width="16" height="16"/>
            <subimage name="tile_grass"         width="16" height="16"/>
            <subimage name="tile_brush"         width="16" height="16"/>
            <subimage name="tile_forest"        width="16" height="16"/>
            <subimage name="tile_hills"         width="16" height="16"/>
            <subimage name="tile_mountains"     width="16" height="16"/>
            <subimage name="tile_dungeon"       width="16" height="16"/>
            <subimage name="tile_city"          width="16" height="16"/>
            <subimage name="tile_castle"        width="16" height="16"/>
            <subimage name="tile_town"          width="16" height="16"/>
            <subimage name="tile_lcb_west"      width="16" height="16"/>
            <subimage name="tile_lcb_entrance"  width="16" height="16"/>
            <subimage name="tile_lcb_east"      width="16" height="16"/>
            <subimage name="tile_ship"          width="16" height="64"/>
            <subimage name="tile_horse"         width="16" height="32"/>
            <subimage name="tile_dungeon_floor" width="16" height="16"/>
            <subimage name="tile_bridge"        width="16" height="16"/>
            <subimage name="tile_balloon"       width="16" height="16"/>
            <subimage name="tile_bridge_pieces" width="16" height="32"/>
            <subimage name="tile_up_ladder"     width="16" height="16"/>
            <subimage name="tile_down_ladder"   width="16" height="16"/>
            <subimage name="tile_ruins"         width="16" height="16"/>
            <subimage name="tile_shrine"        width="16" height="16"/>
            <subimage name="tile_avatar"        width="16" height="16"/>
            <subimage name="tile_mage"          width="16" height="32"/>
            <subimage name="tile_bard"          width="16" height="32"/>
            <subimage name="tile_fighter"       width="16" height="32"/>
            <subimage name="tile_druid"         width="16" height="32"/>
            <subimage name="tile_tinker"        width="16" height="32"/>
            <subimage name="tile_paladin"       width="16" height="32"/>
            <subimage name="tile_ranger"        width="16" height="32"/>
            <subimage name="tile_shepherd"      width="16" height="32"/>
            <subimage name="tile_column"        width="16" height="16"/>
            <subimage name="tile_solids"        width="16" height="64"/>
            <subimage name="tile_shipmast"      width="16" height="16"/>
            <subimage name="tile_shipwheel"     width="16" height="16"/>
            <subimage name="tile_rocks"         width="16" height="16"/>
            <subimage name="tile_corpse"        width="16" height="16"/>
            <subimage name="tile_stone_wall"    width="16" height="16"/>
            <subimage name="tile_locked_door"   width="16" height="16"/>
            <subimage name="tile_door"          width="16" height="16"/>
            <subimage name="tile_chest"         width="16" height="16"/>
            <subimage name="tile_ankh"          width="16" height="16"/>
            <subimage name="tile_brick_floor"   width="16" height="16"/>
            <subimage name="tile_wood_floor"    width="16" height="16"/>
            <subimage name="tile_moongate_opening" width="16" height="48"/>
            <subimage name="tile_moongate"      width="16" height="16"/>
            <subimage name="tile_poison_field"  width="16" height="16"/>
            <subimage name="tile_energy_field"  width="16" height="16"/>
            <subimage name="tile_fire_field"    width="16" height="16"/>
            <subimage name="tile_sleep_field"   width="16" height="16"/>
            <subimage name="tile_solid"         width="16" height="16"/>
            <subimage name="tile_secret_door"   width="16" height="16"/>
            <subimage name="tile_altar"         width="16" height="16"/>
            <subimage name="tile_campfire"      width="16" height="16"/>
            <subimage name="tile_lava"          width="16" height="16"/>
            <subimage name="tile_miss_flash"    width="16" height="16"/>
            <subimage name="tile_magic_flash"   width="16" height="16"/>
            <subimage name="tile_hit_flash"     width="16" height="16"/>
            <subimage name="tile_guard"         width="16" height="32"/>
            <subimage name="tile_villager"      width="16" height="32"/>
            <subimage name="tile_bard_singing"  width="16" height="32"/>
            <subimage name="tile_jester"        width="16" height="32"/>
            <subimage name="tile_beggar"        width="16" height="32"/>
            <subimage name="tile_child"         width="16" height="32"/>
            <subimage name="tile_bull"          width="16" height="32"/>
            <subimage name="tile_lord_british"  width="16" height="32"/>
            <subimage name="tile_A"             width="16" height="16"/>
            <subimage name="tile_B"             width="16" height="16"/>
            <subimage name="tile_C"             width="16" height="16"/>
            <subimage name="tile_D"             width="16" height="16"/>
            <subimage name="tile_E"             width="16" height="16"/>
            <subimage name="tile_F"             width="16" height="16"/>
            <subimage name="tile_G"             width="16" height="16"/>
            <subimage name="tile_H"             width="16" height="16"/>
            <subimage name="tile_I"             width="16" height="16"/>
            <subimage name="tile_J"             width="16" height="16"/>
            <subimage name="tile_K"             width="16" height="16"/>
            <subimage name="tile_L"             width="16" height="16"/>
            <subimage name="tile_M"             width="16" height="16"/>
            <subimage name="tile_N"             width="16" height="16"/>
            <subimage name="tile_O"             width="16" height="16"/>
            <subimage name="tile_P"             width="16" height="16"/>
            <subimage name="tile_Q"             width="16" height="16"/>
            <subimage name="tile_R"             width="16" height="16"/>
            <subimage name="tile_S"             width="16" height="16"/>
            <subimage name="tile_T"             width="16" height="16"/>
            <subimage name="tile_U"             width="16" height="16"/>
            <subimage name="tile_V"             width="16" height="16"/>
            <subimage name="tile_W"             width="16" height="16"/>
            <subimage name="tile_X"             width="16" height="16"/>
            <subimage name="tile_Y"             width="16" height="16"/>
            <subimage name="tile_Z"             width="16" height="16"/>
            <subimage name="tile_space"         width="16" height="16"/>
            <subimage name="tile_spacers"       width="16" height="48"/>
            <subimage name="tile_black"         width="16" height="16"/>
            <subimage name="tile_brick_wall"    width="16" height="16"/>

            <!-- Water monsters -->
            <subimage name="tile_pirate_ship"   width="16" height="64"/>
            <subimage name="tile_nixie"         width="16" height="32"/>
            <subimage name="tile_giant_squid"   width="16" height="32"/>
            <subimage name="tile_sea_serpent"   width="16" height="32"/>
            <subimage name="tile_sea_horse"     width="16" height="32"/>
            <subimage name="tile_whirlpool"     width="16" height="32"/>
            <subimage name="tile_twister"       width="16" height="32"/>

            <!-- Land monsters -->
            <subimage name="tile_rat"           width="16" height="64"/>
            <subimage name="tile_bat"           width="16" height="64"/>
            <subimage name="tile_spider"        width="16" height="64"/>
            <subimage name="tile_ghost"         width="16" height="64"/>
            <subimage name="tile_slime"         width="16" height="64"/>
            <subimage name="tile_troll"         width="16" height="64"/>
            <subimage name="tile_gremlin"       width="16" height="64"/>
            <subimage name="tile_mimic"         width="16" height="64"/>
            <subimage name="tile_reaper"        width="16" height="64"/>
            <subimage name="tile_insect_swarm"  width="16" height="64"/>
            <subimage name="tile_gazer"         width="16" height="64"/>
            <subimage name="tile_phantom"       width="16" height="64"/>
            <subimage name="tile_orc"           width="16" height="64"/>
            <subimage name="tile_skeleton"      width="16" height="64"/>
            <subimage name="tile_rogue"         width="16" height="64"/>
            <subimage name="tile_python"        width="16" height="64"/>
            <subimage name="tile_ettin"         width="16" height="64"/>
            <subimage name="tile_headless"      width="16" height="64"/>
            <subimage name="tile_cyclops"       width="16" height="64"/>
            <subimage name="tile_wisp"          width="16" height="64"/>
            <subimage name="tile_evil_mage"     width="16" height="64"/>
