=== harrytyp/comiupscale/scummvm/fork/devtools/create_ultima/files/ultima4/conf/dtd/tileRules.dtd
<!-- $Id: tileRules.dtd 2785 2011-01-24 07:24:12Z darren_janeczek $ -->

<!ENTITY % bool '( true | false )'>
<!ENTITY % dir '( west | north | east | south | advance | retreat | all )'>
<!ENTITY % effect '( fire | sleep | poison | poisonField | electricity | lava )'>
<!ENTITY % speed '( slow | vslow | vvslow )'>

<!ELEMENT tileRules ( rule+ ) >

<!ELEMENT rule EMPTY >
<!ATTLIST rule name               CDATA    #REQUIRED
               balloon            %bool;   #IMPLIED
               canattackover      %bool;   #IMPLIED
               canlandballoon     %bool;   #IMPLIED
               cantwalkoff        %dir;    #IMPLIED
               cantwalkon         %dir;    #IMPLIED
               chest              %bool;   #IMPLIED
               dispel             %bool;   #IMPLIED
               door               %bool;   #IMPLIED
               effect             %effect; #IMPLIED
               horse              %bool;   #IMPLIED
               lockeddoor         %bool;   #IMPLIED
               creatureunwalkable %bool;   #IMPLIED
               replacement        %bool;   #IMPLIED
               onWaterOnlyReplacement %bool; #IMPLIED
               sailable           %bool;   #IMPLIED
               ship               %bool;   #IMPLIED
               speed              %speed;  #IMPLIED
               swimable           %bool;   #IMPLIED
               talkover           %bool;   #IMPLIED
               unflyable          %bool;   #IMPLIED
               livingthing        %bool;   #IMPLIED>

=== harrytyp/comiupscale/scummvm/fork/devtools/create_ultima/files/ultima4/conf/tileRules.xml
<?xml version="1.0"?>
<!DOCTYPE tileRules SYSTEM "dtd/tileRules.dtd">
<!-- $Id: tileRules.xml 3082 2014-09-10 01:05:01Z darren_janeczek $ -->
<tileRules>
    <rule name="default"/>
    <rule name="water" cantwalkon="all" swimable="true" sailable="true" onWaterOnlyReplacement="true"/>
    <rule name="shallows" cantwalkon="all" swimable="true" onWaterOnlyReplacement="true"/>
    <rule name="swamp" speed="slow" effect="poison" />
    <rule name="grass" canlandballoon="true" replacement="true"/>
    <rule name="brush" speed="vslow" />
    <rule name="hills" speed="vvslow" />
    <rule name="mountains" cantwalkon="all" unflyable="true" creatureunwalkable="true"/>
    <rule name="lcb" cantwalkon="all" creatureunwalkable="true"/>
    <rule name="lcb_entrance" cantwalkon="south" cantwalkoff="north" creatureunwalkable="true"/>
    <rule name="ship" ship="true" creatureunwalkable="true"/>
    <rule name="horse" horse="true" creatureunwalkable="true"/>
    <rule name="floors" replacement="true"/>
    <rule name="balloon" balloon="true" creatureunwalkable="true"/>
    <rule name="person" cantwalkon="all" livingthing="true"/>
    <rule name="solid" cantwalkon="all"/>
    <rule name="solid_attackover" cantwalkon="all" canattackover="true"/>
    <rule name="walls" cantwalkon="all" unflyable="true"/>
    <rule name="locked_door" cantwalkon="all" lockeddoor="true"/>
    <rule name="door" cantwalkon="all" door="true"/>
    <rule name="secret_door" cantwalkon="retreat"/>
    <rule name="chest" chest="true"/>
    <rule name="poison_field" effect="poisonField" dispel="true"/>
    <rule name="energy_field" cantwalkon="all" effect="electricity" creatureunwalkable="true" unflyable="true" dispel="true"/>
    <rule name="fire_field" speed="vvslow" effect="fire" dispel="true"/>
    <rule name="sleep_field" effect="sleep" dispel="true"/>
    <rule name="lava" effect="lava" replacement="true"/>
    <rule name="signs" cantwalkon="all" talkover="true"/>
    <rule name="spacers" cantwalkon="all"/>
    <rule name="monster" cantwalkon="all" livingthing="true"/>

    <!-- Dungeon tile rules -->
    <rule name="dng_altar" creatureunwalkable="true" unflyable="true"/>
    <rule name="dng_door" cantwalkon="retreat"/>
    <rule name="dng_room" creatureunwalkable="true" cantwalkon="retreat" unflyable="true"/>
</tileRules>
